name = "BiophysicalBehaviour"
uuid = "17159459-d6a3-4a3d-a4c5-9872d9e70704"
authors = ["Michael Kearney and Rafael Schouten"]
version = "0.1.0"

[deps]
BiophysicalGeometry = "06c61620-4f66-4020-a018-07befe374221"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
HeatExchange = "720bd838-cdd6-4aad-926b-452b962dce21"
ModelParameters = "4744a3fa-6c31-4707-899e-a3298e4618ad"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMoles = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"

[sources]
BiophysicalGeometry = {rev = "main", url = "https://github.com/BiophysicalEcology/BiophysicalGeometry.jl"}
HeatExchange = {rev = "main", url = "https://github.com/BiophysicalEcology/HeatExchange.jl"}

[compat]
Aqua = "0.8"
BiophysicalGeometry = "0.1.0"
ConstructionBase = "1.6.0"
CSV = "0.10.15"
DataFrames = "1"
HeatExchange = "0.1.0"
ModelParameters = "0.4"
SafeTestsets = "0.1"
Test = "1"
Unitful = "1"
UnitfulMoles = "0.1.1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "SafeTestsets", "Test"]
